// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../categoria/domain/entities/categoria.dart';
import '../novo_pedido/domain/entities/cliente.dart';
import '../novo_pedido/domain/entities/forma_pagamento.dart';
import '../novo_pedido/domain/entities/item_pedido.dart';
import '../novo_pedido/domain/entities/pedido.dart';
import '../produto/domain/entities/produto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2790766718378610696),
      name: 'CategoriaEntity',
      lastPropertyId: const obx_int.IdUid(11, 3087759722547830307),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2490341766168362116),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3214118195684898196),
            name: 'nome',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6187860167254685327),
            name: 'descricao',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 9082868744933548302),
            name: 'ativo',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8678661725529152717),
            name: 'dataCadastro',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5654339136591092103),
            name: 'orderm',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3087759722547830307),
            name: 'selecionado',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 8584595762100547294),
      name: 'ProdutoEntity',
      lastPropertyId: const obx_int.IdUid(18, 3598267433411002787),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4649621048714799332),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2743258171475514137),
            name: 'nome',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1539619968326158159),
            name: 'descricao',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1591871108922242247),
            name: 'ativo',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6818469028862893682),
            name: 'imagem',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5303683702648761882),
            name: 'deleteDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6265625626263060650),
            name: 'valorVenda',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2690960657540396890),
            name: 'valorCusto',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3370093621230264520),
            name: 'observacao',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4752558482630069935),
            name: 'quantidadeItem',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 723939335361320896),
            name: 'idCategoria',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 5201257947978371163),
            name: 'nomeCategoria',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 1964834842719221243),
            name: 'codigo',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 8237574970897318776),
            name: 'quantidadeEstoque',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 6062530122507368091),
            name: 'quantidadePeso',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1072223905941683785),
            name: 'quantidadeVenda',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 3598267433411002787),
            name: 'categoriaId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 5197689146029817673),
            relationTarget: 'CategoriaEntity')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 6797784210184068166),
      name: 'Cliente',
      lastPropertyId: const obx_int.IdUid(3, 4556642727379941490),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4891383075842640743),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8132532633223731916),
            name: 'nome',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4556642727379941490),
            name: 'telefone',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4897406971331269154),
      name: 'FormaPagamento',
      lastPropertyId: const obx_int.IdUid(3, 5059934973399923068),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2233947008803650845),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8953636282519179285),
            name: 'nome',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5059934973399923068),
            name: 'ativo',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 7044709983208515468),
      name: 'ItemPedido',
      lastPropertyId: const obx_int.IdUid(6, 8735406581077311255),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4671715480820807664),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5483547667267861711),
            name: 'idProduto',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5412950554528562238),
            name: 'quantidade',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3563646358878187087),
            name: 'valorVenda',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8735406581077311255),
            name: 'idPedido',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 2202957339522128347),
      name: 'Pedido',
      lastPropertyId: const obx_int.IdUid(7, 3688276844260731527),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4375646955856020829),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5630565880197754646),
            name: 'descricao',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3942514709482339474),
            name: 'jaPagou',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 709101780233656801),
            name: 'dataCadastro',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8413522692755011882),
            name: 'total',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2577856831676958084),
            name: 'idCliente',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3688276844260731527),
            name: 'idFormaPagamento',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 2202957339522128347),
      lastIndexId: const obx_int.IdUid(2, 5197689146029817673),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [2113825209199880269],
      retiredIndexUids: const [599111487119005814],
      retiredPropertyUids: const [
        4704055095269401269,
        136769142390289349,
        3702833437645989619,
        3445808947160221001,
        1673443576338422149,
        5896487417719927772,
        7575156137654867624,
        2042895103175771715,
        8839237075141299786,
        4948498373581813054,
        4523840171198971608,
        4055925582938483673
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoriaEntity: obx_int.EntityDefinition<CategoriaEntity>(
        model: _entities[0],
        toOneRelations: (CategoriaEntity object) => [],
        toManyRelations: (CategoriaEntity object) => {},
        getId: (CategoriaEntity object) => object.id,
        setId: (CategoriaEntity object, int id) {
          object.id = id;
        },
        objectToFB: (CategoriaEntity object, fb.Builder fbb) {
          final nomeOffset =
              object.nome == null ? null : fbb.writeString(object.nome!);
          final descricaoOffset = object.descricao == null
              ? null
              : fbb.writeString(object.descricao!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(6, descricaoOffset);
          fbb.addBool(7, object.ativo);
          fbb.addInt64(8, object.dataCadastro?.millisecondsSinceEpoch);
          fbb.addInt64(9, object.orderm);
          fbb.addBool(10, object.selecionado);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dataCadastroValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final descricaoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final ativoParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 18);
          final dataCadastroParam = dataCadastroValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dataCadastroValue);
          final ordermParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final selecionadoParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 24);
          final object = CategoriaEntity(
              nome: nomeParam,
              descricao: descricaoParam,
              ativo: ativoParam,
              dataCadastro: dataCadastroParam,
              orderm: ordermParam,
              selecionado: selecionadoParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ProdutoEntity: obx_int.EntityDefinition<ProdutoEntity>(
        model: _entities[1],
        toOneRelations: (ProdutoEntity object) => [object.categoria],
        toManyRelations: (ProdutoEntity object) => {},
        getId: (ProdutoEntity object) => object.id,
        setId: (ProdutoEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ProdutoEntity object, fb.Builder fbb) {
          final nomeOffset =
              object.nome == null ? null : fbb.writeString(object.nome!);
          final descricaoOffset = object.descricao == null
              ? null
              : fbb.writeString(object.descricao!);
          final imagemOffset =
              object.imagem == null ? null : fbb.writeString(object.imagem!);
          final observacaoOffset = object.observacao == null
              ? null
              : fbb.writeString(object.observacao!);
          final nomeCategoriaOffset = object.nomeCategoria == null
              ? null
              : fbb.writeString(object.nomeCategoria!);
          fbb.startTable(19);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(2, descricaoOffset);
          fbb.addBool(3, object.ativo);
          fbb.addOffset(4, imagemOffset);
          fbb.addInt64(5, object.deleteDate?.millisecondsSinceEpoch);
          fbb.addFloat64(6, object.valorVenda);
          fbb.addFloat64(7, object.valorCusto);
          fbb.addOffset(8, observacaoOffset);
          fbb.addInt64(9, object.quantidadeItem);
          fbb.addInt64(10, object.idCategoria);
          fbb.addOffset(11, nomeCategoriaOffset);
          fbb.addInt64(12, object.codigo);
          fbb.addInt64(13, object.quantidadeEstoque);
          fbb.addInt64(14, object.quantidadePeso);
          fbb.addInt64(15, object.quantidadeVenda);
          fbb.addInt64(17, object.categoria.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final deleteDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final ativoParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 10);
          final imagemParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final deleteDateParam = deleteDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(deleteDateValue);
          final idCategoriaParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 24);
          final valorVendaParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 16);
          final valorCustoParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 18);
          final codigoParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final quantidadeEstoqueParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 30);
          final descricaoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final observacaoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final quantidadeItemParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final quantidadePesoParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 32);
          final quantidadeVendaParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
          final object = ProdutoEntity(
              nome: nomeParam,
              ativo: ativoParam,
              imagem: imagemParam,
              deleteDate: deleteDateParam,
              idCategoria: idCategoriaParam,
              valorVenda: valorVendaParam,
              valorCusto: valorCustoParam,
              codigo: codigoParam,
              quantidadeEstoque: quantidadeEstoqueParam,
              descricao: descricaoParam,
              observacao: observacaoParam,
              quantidadeItem: quantidadeItemParam,
              quantidadePeso: quantidadePesoParam,
              quantidadeVenda: quantidadeVendaParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..nomeCategoria = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 26);
          object.categoria.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          object.categoria.attach(store);
          return object;
        }),
    Cliente: obx_int.EntityDefinition<Cliente>(
        model: _entities[2],
        toOneRelations: (Cliente object) => [],
        toManyRelations: (Cliente object) => {},
        getId: (Cliente object) => object.id,
        setId: (Cliente object, int id) {
          object.id = id;
        },
        objectToFB: (Cliente object, fb.Builder fbb) {
          final nomeOffset =
              object.nome == null ? null : fbb.writeString(object.nome!);
          final telefoneOffset = object.telefone == null
              ? null
              : fbb.writeString(object.telefone!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(2, telefoneOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final telefoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final object = Cliente(nome: nomeParam, telefone: telefoneParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    FormaPagamento: obx_int.EntityDefinition<FormaPagamento>(
        model: _entities[3],
        toOneRelations: (FormaPagamento object) => [],
        toManyRelations: (FormaPagamento object) => {},
        getId: (FormaPagamento object) => object.id,
        setId: (FormaPagamento object, int id) {
          object.id = id;
        },
        objectToFB: (FormaPagamento object, fb.Builder fbb) {
          final nomeOffset =
              object.nome == null ? null : fbb.writeString(object.nome!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.addBool(2, object.ativo);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final ativoParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 8);
          final object = FormaPagamento(nome: nomeParam, ativo: ativoParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ItemPedido: obx_int.EntityDefinition<ItemPedido>(
        model: _entities[4],
        toOneRelations: (ItemPedido object) => [],
        toManyRelations: (ItemPedido object) => {},
        getId: (ItemPedido object) => object.id,
        setId: (ItemPedido object, int id) {
          object.id = id;
        },
        objectToFB: (ItemPedido object, fb.Builder fbb) {
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.idProduto);
          fbb.addInt64(2, object.quantidade);
          fbb.addFloat64(3, object.valorVenda);
          fbb.addInt64(5, object.idPedido);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idProdutoParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final idPedidoParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final quantidadeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final valorVendaParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = ItemPedido(
              idProduto: idProdutoParam,
              idPedido: idPedidoParam,
              quantidade: quantidadeParam,
              valorVenda: valorVendaParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Pedido: obx_int.EntityDefinition<Pedido>(
        model: _entities[5],
        toOneRelations: (Pedido object) => [],
        toManyRelations: (Pedido object) => {},
        getId: (Pedido object) => object.id,
        setId: (Pedido object, int id) {
          object.id = id;
        },
        objectToFB: (Pedido object, fb.Builder fbb) {
          final descricaoOffset = object.descricao == null
              ? null
              : fbb.writeString(object.descricao!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, descricaoOffset);
          fbb.addBool(2, object.jaPagou);
          fbb.addInt64(3, object.dataCadastro?.millisecondsSinceEpoch);
          fbb.addFloat64(4, object.total);
          fbb.addInt64(5, object.idCliente);
          fbb.addInt64(6, object.idFormaPagamento);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dataCadastroValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final idClienteParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final descricaoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final idFormaPagamentoParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final jaPagouParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 8);
          final dataCadastroParam = dataCadastroValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dataCadastroValue);
          final object = Pedido(
              idCliente: idClienteParam,
              descricao: descricaoParam,
              idFormaPagamento: idFormaPagamentoParam,
              jaPagou: jaPagouParam,
              dataCadastro: dataCadastroParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..total =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoriaEntity] entity fields to define ObjectBox queries.
class CategoriaEntity_ {
  /// see [CategoriaEntity.id]
  static final id =
      obx.QueryIntegerProperty<CategoriaEntity>(_entities[0].properties[0]);

  /// see [CategoriaEntity.nome]
  static final nome =
      obx.QueryStringProperty<CategoriaEntity>(_entities[0].properties[1]);

  /// see [CategoriaEntity.descricao]
  static final descricao =
      obx.QueryStringProperty<CategoriaEntity>(_entities[0].properties[2]);

  /// see [CategoriaEntity.ativo]
  static final ativo =
      obx.QueryBooleanProperty<CategoriaEntity>(_entities[0].properties[3]);

  /// see [CategoriaEntity.dataCadastro]
  static final dataCadastro =
      obx.QueryDateProperty<CategoriaEntity>(_entities[0].properties[4]);

  /// see [CategoriaEntity.orderm]
  static final orderm =
      obx.QueryIntegerProperty<CategoriaEntity>(_entities[0].properties[5]);

  /// see [CategoriaEntity.selecionado]
  static final selecionado =
      obx.QueryBooleanProperty<CategoriaEntity>(_entities[0].properties[6]);
}

/// [ProdutoEntity] entity fields to define ObjectBox queries.
class ProdutoEntity_ {
  /// see [ProdutoEntity.id]
  static final id =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[0]);

  /// see [ProdutoEntity.nome]
  static final nome =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[1]);

  /// see [ProdutoEntity.descricao]
  static final descricao =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[2]);

  /// see [ProdutoEntity.ativo]
  static final ativo =
      obx.QueryBooleanProperty<ProdutoEntity>(_entities[1].properties[3]);

  /// see [ProdutoEntity.imagem]
  static final imagem =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[4]);

  /// see [ProdutoEntity.deleteDate]
  static final deleteDate =
      obx.QueryDateProperty<ProdutoEntity>(_entities[1].properties[5]);

  /// see [ProdutoEntity.valorVenda]
  static final valorVenda =
      obx.QueryDoubleProperty<ProdutoEntity>(_entities[1].properties[6]);

  /// see [ProdutoEntity.valorCusto]
  static final valorCusto =
      obx.QueryDoubleProperty<ProdutoEntity>(_entities[1].properties[7]);

  /// see [ProdutoEntity.observacao]
  static final observacao =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[8]);

  /// see [ProdutoEntity.quantidadeItem]
  static final quantidadeItem =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[9]);

  /// see [ProdutoEntity.idCategoria]
  static final idCategoria =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[10]);

  /// see [ProdutoEntity.nomeCategoria]
  static final nomeCategoria =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[11]);

  /// see [ProdutoEntity.codigo]
  static final codigo =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[12]);

  /// see [ProdutoEntity.quantidadeEstoque]
  static final quantidadeEstoque =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[13]);

  /// see [ProdutoEntity.quantidadePeso]
  static final quantidadePeso =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[14]);

  /// see [ProdutoEntity.quantidadeVenda]
  static final quantidadeVenda =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[15]);

  /// see [ProdutoEntity.categoria]
  static final categoria =
      obx.QueryRelationToOne<ProdutoEntity, CategoriaEntity>(
          _entities[1].properties[16]);
}

/// [Cliente] entity fields to define ObjectBox queries.
class Cliente_ {
  /// see [Cliente.id]
  static final id =
      obx.QueryIntegerProperty<Cliente>(_entities[2].properties[0]);

  /// see [Cliente.nome]
  static final nome =
      obx.QueryStringProperty<Cliente>(_entities[2].properties[1]);

  /// see [Cliente.telefone]
  static final telefone =
      obx.QueryStringProperty<Cliente>(_entities[2].properties[2]);
}

/// [FormaPagamento] entity fields to define ObjectBox queries.
class FormaPagamento_ {
  /// see [FormaPagamento.id]
  static final id =
      obx.QueryIntegerProperty<FormaPagamento>(_entities[3].properties[0]);

  /// see [FormaPagamento.nome]
  static final nome =
      obx.QueryStringProperty<FormaPagamento>(_entities[3].properties[1]);

  /// see [FormaPagamento.ativo]
  static final ativo =
      obx.QueryBooleanProperty<FormaPagamento>(_entities[3].properties[2]);
}

/// [ItemPedido] entity fields to define ObjectBox queries.
class ItemPedido_ {
  /// see [ItemPedido.id]
  static final id =
      obx.QueryIntegerProperty<ItemPedido>(_entities[4].properties[0]);

  /// see [ItemPedido.idProduto]
  static final idProduto =
      obx.QueryIntegerProperty<ItemPedido>(_entities[4].properties[1]);

  /// see [ItemPedido.quantidade]
  static final quantidade =
      obx.QueryIntegerProperty<ItemPedido>(_entities[4].properties[2]);

  /// see [ItemPedido.valorVenda]
  static final valorVenda =
      obx.QueryDoubleProperty<ItemPedido>(_entities[4].properties[3]);

  /// see [ItemPedido.idPedido]
  static final idPedido =
      obx.QueryIntegerProperty<ItemPedido>(_entities[4].properties[4]);
}

/// [Pedido] entity fields to define ObjectBox queries.
class Pedido_ {
  /// see [Pedido.id]
  static final id =
      obx.QueryIntegerProperty<Pedido>(_entities[5].properties[0]);

  /// see [Pedido.descricao]
  static final descricao =
      obx.QueryStringProperty<Pedido>(_entities[5].properties[1]);

  /// see [Pedido.jaPagou]
  static final jaPagou =
      obx.QueryBooleanProperty<Pedido>(_entities[5].properties[2]);

  /// see [Pedido.dataCadastro]
  static final dataCadastro =
      obx.QueryDateProperty<Pedido>(_entities[5].properties[3]);

  /// see [Pedido.total]
  static final total =
      obx.QueryDoubleProperty<Pedido>(_entities[5].properties[4]);

  /// see [Pedido.idCliente]
  static final idCliente =
      obx.QueryIntegerProperty<Pedido>(_entities[5].properties[5]);

  /// see [Pedido.idFormaPagamento]
  static final idFormaPagamento =
      obx.QueryIntegerProperty<Pedido>(_entities[5].properties[6]);
}
