name: gestor_vendas
description: "Vendas Ebel Tec"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.17.9

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.2
  provider: ^6.1.2
  intl: ^0.18.0
  flutter_phoenix: ^1.1.1
  bot_toast: ^4.1.3
  extended_masked_text: ^2.3.1
  cpf_cnpj_validator: ^2.0.0
  easy_mask: ^2.0.1
  mask_text_input_formatter: ^2.9.0
  another_xlider: ^3.0.1
  geolocator: ^11.0.0
  search_cep: ^4.0.0+1
  flutter_esc_pos_utils: ^1.0.0
  flutter_pos_printer_platform: ^1.4.1
  hive: ^2.2.3
  shared_preferences: ^2.1.0
  flutter_colorpicker: ^1.0.3
  fl_chart: ^0.60.0
  syncfusion_flutter_charts: ^20.4.49
  horizontal_week_calendar: 0.0.1
  package_info_plus: ^4.2.0
  get: ^4.6.5
  flutter_slider_drawer: ^2.1.3
  gerencianet: ^1.2.1
  aligned_dialog: ^0.0.7
  url_launcher: ^6.1.10
  whatsapp_unilink: ^2.1.0
  image_cropper: ^4.0.0
  crop_your_image: ^1.0.1
  image: ^4.0.17
  image_picker: ^0.8.5+3
  adaptive_theme: ^3.6.0
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^3.0.0

objectbox:
  output_dir: database

flutter:
  uses-material-design: true
